Update AvaTax SDK
boomerdigital/solidus_avatax_certified pull request #186
Opened 2024-09-10 08:31 UTC by filippoliverani

2024-09-10 13:12 UTC, Noah-Silvera requested changes
Mostly just questions on documentation and communication to consumers! I reviewed the code, and reviewed and compared the two API's (official and skukx) to double check we ported this code correctly, and it all looks good! Would like to test this on a running app before I approve.

Just requesting changes on figuring out the communication to consumers of the gem/changelog updates.

2024-09-11 10:49 UTC, filippoliverani commented on app/models/solidus_avatax_certified/avatax_log.rb
> +        @logger ||= ::Spree::Avatax::Config.logger.presence || Logger.new("#{Rails.root}/log/avatax.log", schedule)
It shouldn't be needed because it's already required by Rails and other gems, but we can do an explicit `require` anyway just in case 👍

2024-09-11 10:50 UTC, filippoliverani commented on app/models/solidus_avatax_certified/response/base.rb
> -      rescue StandardError
Yes, I proposed a major version bump because there are couple of possible breaking changes, I'll update the changelog accordingly 👍

2024-09-11 11:47 UTC, filippoliverani commented on app/models/tax_svc.rb
> +    SolidusAvataxCertified::Response::Base.new(client.list_my_subscriptions)
Yes, while testing the integration I found out that the previous endpoint (TaxRatesByPostalCode) might return an error for non-US Avalara company codes. I'll updated the commit description to make that clear 👍

2024-09-11 11:53 UTC, filippoliverani commented on app/models/tax_svc.rb
> -      headers: AVATAX_HEADERS
Right, on it! 👍

2024-09-17 12:13 UTC, AlessioRocco approved these changes
I’ve reviewed the code and compared both APIs (official and skukx) to ensure the port was done correctly, and everything checks out! I don't see major issues since you have kept the backward compatibility, like @Noah-Silvera suggested we should test it on a real application, and then we should be good to go.

2024-09-17 14:40 UTC, Noah-Silvera approved these changes
Thanks for addressing my comments! Looks fantastic, pending testing on a real app!

2024-09-17 14:40 UTC, Noah-Silvera commented on app/models/solidus_avatax_certified/response/base.rb
> -      rescue StandardError
Sounds good to me! Thanks @filippoliverani

2024-09-17 14:47 UTC, dhonig commented
Excited to get this merged.  I might be ok with merging it even though the older sqlite 3.0 circle ci test fails?  thoughts?

2024-09-17 14:54 UTC, Noah-Silvera commented
Considering ruby 3.0 is EOL maintenance wise, I'm ok with that test failing.

We should probably remove that test altogether and add tests for ruby 3.3 and 3.4 instead! Then we cover all the actively maintained versions of ruby

2024-09-18 10:33 UTC, filippoliverani commented
> @Noah-Silvera great suggestion lets remove the failing 3.0 tests and add the others.

Yeah, good idea! I updated CircleCi params in https://github.com/boomerdigital/solidus_avatax_certified/pull/186/commits/e1596653132c2bf5e055e1b784acc8c4e005aa45 👍

2024-09-20 07:32 UTC, filippoliverani commented
> pending testing on a real app!

I started testing the branch on a real app, I'll let you know if I find any issue 👍

2024-09-23 12:11 UTC, Noah-Silvera commented on app/models/tax_svc.rb
> +      faraday_response: true
@filippoliverani I'm a little bit confused now as to whether adding `faraday_response: true` here is a breaking change or not

It looks like the default in the official client is `false` and has been for a while, and it doesn't look to me like we overrode this before in this repo

https://github.com/avadev/AvaTax-REST-V2-Ruby-SDK/blob/7f55f09dbf4ae80e7d4883032c54b50f520aeb6c/lib/avatax/configuration.rb#L38

2024-09-23 14:30 UTC, filippoliverani commented on app/models/tax_svc.rb
> +      faraday_response: true
The [old SKD returned a Faraday respose by default](https://github.com/skukx/avatax/blob/9855aeb67c6c99c7247081eadba9a0970a9fa4da/lib/avatax/response.rb#L2), this is needed to have the same behavior and avoiud a breaking change 👍

2024-09-24 13:19 UTC, Noah-Silvera commented on app/models/tax_svc.rb
> +      faraday_response: true
THANK YOUUUUU. I see I see

2024-09-30 15:41 UTC, filippoliverani commented
@dhonig @Noah-Silvera We haven't found any regressions when testing on a real application, If no one else wants to run additional tests, I think it could be merged 🙌

2024-09-30 15:48 UTC, dhonig commented
:shipit:  Thanks again!

2024-10-01 11:27 UTC, kennyadsl approved these changes
Thanks Fil, and everyone involved!

2024-10-01 11:27 UTC, merged